
# Copyright 2021 .
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from setuptools import setup, find_packages
import datetime as dt


package_nm = 'sklearnserver'
__version__ = "0.1.0"

tests_require = [
    'pytest',
    'pytest-asyncio',
    'pytest-tornasync',
    'mypy'
]

aix_requires = [
    "kfserving>=0.5.0",
    "argparse >= 1.4.0",
    "aix360 >= 0.1.0",
    "lime >= 0.1.1.37",
    "nest_asyncio>=1.4.0"
]

alibi_requires = [
    "kfserving>=0.5.0",
    "pandas>=0.24.2",
    "nest_asyncio>=1.4.0",
    "alibi==0.5.5",
    "scikit-learn == 0.20.3",
    "argparse>=1.4.0",
    "requests>=2.22.0",
    "joblib>=0.13.2",
    "dill>=0.3.0",
    "grpcio>=1.22.0",
    "xgboost==1.0.2",
    "shap==0.36.0",
    "numpy<1.19.0"
]

lgb_requires = [
    "kfserving>=0.4.0",
    "lightgbm == 2.3.1",
    "pandas == 0.25.3",
    "argparse >= 1.4.0"
]

pmml_requires = [
    "kfserving>=0.5.0",
    "pypmml == 0.9.7",
]

pytorch_requires = [
    "kfserving>=0.5.0",
    "torch >= 1.0.0",
    "torchvision >= 0.2.0"
]

sklearn_requires = [
    "kfserving>=0.5.0",
    # "scikit-learn == 0.20.3",
    "scikit-learn >= 0.20.3",
    "joblib >= 0.13.0"
]

xgb_requires = [
    "kfserving>=0.5.0",
    "xgboost == 0.82",
    "scikit-learn == 0.20.3",
]


with open(f'{package_nm}/__version__.py', 'w') as f:
    version_py_module = f'''#-*- coding: utf-8 -*-
# This file is automatically generated by 'setup.py'
"""
Modified on {dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""
__all__ = ['__version__']

__version__ = '{__version__}'
'''
    f.write(version_py_module)


setup(
    name=package_nm,
    version=__version__,
    author_email='pydemia@gmail.com',
    license='https://github.com/kubeflow/kfserving/LICENSE',
    url='',
    description='Model Server implementation for AI Runtime.',
    long_description=open('README.md').read(),
    python_requires='>3.4',
    packages=find_packages(
        exclude=['contrib', 'docs', 'tests'],
    ),
    install_requires=sklearn_requires,
    tests_require=tests_require,
    extras_require={'test': tests_require}
)
